// Code generated by MockGen. DO NOT EDIT.
// Source: behavior.go
//
// Generated by this command:
//
//	mockgen -source=behavior.go -destination=mock_behavior.go -package=ai
//

// Package ai is a generated GoMock package.
package ai

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTarget is a mock of Target interface.
type MockTarget struct {
	ctrl     *gomock.Controller
	recorder *MockTargetMockRecorder
	isgomock struct{}
}

// MockTargetMockRecorder is the mock recorder for MockTarget.
type MockTargetMockRecorder struct {
	mock *MockTarget
}

// NewMockTarget creates a new mock instance.
func NewMockTarget(ctrl *gomock.Controller) *MockTarget {
	mock := &MockTarget{ctrl: ctrl}
	mock.recorder = &MockTargetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTarget) EXPECT() *MockTargetMockRecorder {
	return m.recorder
}

// MockBehavior is a mock of Behavior interface.
type MockBehavior struct {
	ctrl     *gomock.Controller
	recorder *MockBehaviorMockRecorder
	isgomock struct{}
}

// MockBehaviorMockRecorder is the mock recorder for MockBehavior.
type MockBehaviorMockRecorder struct {
	mock *MockBehavior
}

// NewMockBehavior creates a new mock instance.
func NewMockBehavior(ctrl *gomock.Controller) *MockBehavior {
	mock := &MockBehavior{ctrl: ctrl}
	mock.recorder = &MockBehaviorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBehavior) EXPECT() *MockBehaviorMockRecorder {
	return m.recorder
}

// Action mocks base method.
func (m *MockBehavior) Action(ctx *Context, target Target) Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Action", ctx, target)
	ret0, _ := ret[0].(Action)
	return ret0
}

// Action indicates an expected call of Action.
func (mr *MockBehaviorMockRecorder) Action(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Action", reflect.TypeOf((*MockBehavior)(nil).Action), ctx, target)
}

// ForEachConsideration mocks base method.
func (m *MockBehavior) ForEachConsideration(ctx *Context, target Target, yield func(*Consideration) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForEachConsideration", ctx, target, yield)
}

// ForEachConsideration indicates an expected call of ForEachConsideration.
func (mr *MockBehaviorMockRecorder) ForEachConsideration(ctx, target, yield any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForEachConsideration", reflect.TypeOf((*MockBehavior)(nil).ForEachConsideration), ctx, target, yield)
}

// ID mocks base method.
func (m *MockBehavior) ID() BehaviorID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(BehaviorID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockBehaviorMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockBehavior)(nil).ID))
}

// Name mocks base method.
func (m *MockBehavior) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockBehaviorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockBehavior)(nil).Name))
}

// Provider mocks base method.
func (m *MockBehavior) Provider(ctx *Context) TargetProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provider", ctx)
	ret0, _ := ret[0].(TargetProvider)
	return ret0
}

// Provider indicates an expected call of Provider.
func (mr *MockBehaviorMockRecorder) Provider(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provider", reflect.TypeOf((*MockBehavior)(nil).Provider), ctx)
}

// ShouldAddToHistory mocks base method.
func (m *MockBehavior) ShouldAddToHistory() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldAddToHistory")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldAddToHistory indicates an expected call of ShouldAddToHistory.
func (mr *MockBehaviorMockRecorder) ShouldAddToHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldAddToHistory", reflect.TypeOf((*MockBehavior)(nil).ShouldAddToHistory))
}

// Weight mocks base method.
func (m *MockBehavior) Weight(ctx *Context, target Target) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Weight", ctx, target)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Weight indicates an expected call of Weight.
func (mr *MockBehaviorMockRecorder) Weight(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Weight", reflect.TypeOf((*MockBehavior)(nil).Weight), ctx, target)
}
