// Code generated by MockGen. DO NOT EDIT.
// Source: action.go
//
// Generated by this command:
//
//	mockgen -source=action.go -destination=mock_action.go -package=ai
//

// Package ai is a generated GoMock package.
package ai

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAction is a mock of Action interface.
type MockAction struct {
	ctrl     *gomock.Controller
	recorder *MockActionMockRecorder
	isgomock struct{}
}

// MockActionMockRecorder is the mock recorder for MockAction.
type MockActionMockRecorder struct {
	mock *MockAction
}

// NewMockAction creates a new mock instance.
func NewMockAction(ctrl *gomock.Controller) *MockAction {
	mock := &MockAction{ctrl: ctrl}
	mock.recorder = &MockActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAction) EXPECT() *MockActionMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockAction) Cancel(ctx *Context, target Target) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel", ctx, target)
}

// Cancel indicates an expected call of Cancel.
func (mr *MockActionMockRecorder) Cancel(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockAction)(nil).Cancel), ctx, target)
}

// ID mocks base method.
func (m *MockAction) ID() ActionID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(ActionID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockActionMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockAction)(nil).ID))
}

// ShouldAddToHistory mocks base method.
func (m *MockAction) ShouldAddToHistory() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldAddToHistory")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldAddToHistory indicates an expected call of ShouldAddToHistory.
func (mr *MockActionMockRecorder) ShouldAddToHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldAddToHistory", reflect.TypeOf((*MockAction)(nil).ShouldAddToHistory))
}

// Start mocks base method.
func (m *MockAction) Start(ctx *Context, target Target) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx, target)
}

// Start indicates an expected call of Start.
func (mr *MockActionMockRecorder) Start(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAction)(nil).Start), ctx, target)
}

// Update mocks base method.
func (m *MockAction) Update(ctx *Context, target Target) ActionStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, target)
	ret0, _ := ret[0].(ActionStatus)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockActionMockRecorder) Update(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAction)(nil).Update), ctx, target)
}
