// Code generated by MockGen. DO NOT EDIT.
// Source: consideration.go
//
// Generated by this command:
//
//	mockgen -source=consideration.go -destination=mock_consideration.go -package=ai
//

// Package ai is a generated GoMock package.
package ai

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCurve is a mock of Curve interface.
type MockCurve struct {
	ctrl     *gomock.Controller
	recorder *MockCurveMockRecorder
	isgomock struct{}
}

// MockCurveMockRecorder is the mock recorder for MockCurve.
type MockCurveMockRecorder struct {
	mock *MockCurve
}

// NewMockCurve creates a new mock instance.
func NewMockCurve(ctrl *gomock.Controller) *MockCurve {
	mock := &MockCurve{ctrl: ctrl}
	mock.recorder = &MockCurveMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurve) EXPECT() *MockCurveMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockCurve) Apply(x float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", x)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockCurveMockRecorder) Apply(x any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockCurve)(nil).Apply), x)
}
