// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -destination=mock_provider.go -package=ai
//

// Package ai is a generated GoMock package.
package ai

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTargetProvider is a mock of TargetProvider interface.
type MockTargetProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTargetProviderMockRecorder
	isgomock struct{}
}

// MockTargetProviderMockRecorder is the mock recorder for MockTargetProvider.
type MockTargetProviderMockRecorder struct {
	mock *MockTargetProvider
}

// NewMockTargetProvider creates a new mock instance.
func NewMockTargetProvider(ctrl *gomock.Controller) *MockTargetProvider {
	mock := &MockTargetProvider{ctrl: ctrl}
	mock.recorder = &MockTargetProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetProvider) EXPECT() *MockTargetProviderMockRecorder {
	return m.recorder
}

// ID mocks base method.
func (m *MockTargetProvider) ID() TargetProviderID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(TargetProviderID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockTargetProviderMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockTargetProvider)(nil).ID))
}

// ShouldCache mocks base method.
func (m *MockTargetProvider) ShouldCache() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldCache")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldCache indicates an expected call of ShouldCache.
func (mr *MockTargetProviderMockRecorder) ShouldCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldCache", reflect.TypeOf((*MockTargetProvider)(nil).ShouldCache))
}

// Targets mocks base method.
func (m *MockTargetProvider) Targets(ctx *Context) []Target {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Targets", ctx)
	ret0, _ := ret[0].([]Target)
	return ret0
}

// Targets indicates an expected call of Targets.
func (mr *MockTargetProviderMockRecorder) Targets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Targets", reflect.TypeOf((*MockTargetProvider)(nil).Targets), ctx)
}
